config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :comentarios
  resources :platos
  devise_for :users
  devise_for :restaurantes
  get 'home/index'
  get 'solicitudes', to: 'restaurantes#solicitudes'
  post 'aprobar/:id', to: 'restaurantes#aprobar_solicitud', as: 'aprobar'
  post 'enviar_pedido/:id', to: 'orders#enviar_pedido', as: 'enviar_pedido'
  post 'finalizar_pedido/:id', to: 'orders#finalizar_pedido', as: 'finalizar_pedido'
  get 'pago/:restaurante_id', to: 'orders#pago', as: 'pago'
  get 'mis_platos', to: 'restaurantes#mis_platos', as: 'mis_platos'
  get 'mis_comentarios', to: 'restaurantes#mis_comentarios', as: 'mis_comentarios'
  get 'mis_ordenes', to: 'restaurantes#mis_ordenes', as: 'mis_ordenes'
  post 'add_fav/:id/:nombre', to: 'users#add_fav', as: 'add_fav'
  post 'delete_fav/:nombre', to: 'users#delete_fav', as: 'delete_fav'
  get 'pedidos_usuario', to: 'users#pedidos_usuario', as: 'pedidos_usuario'
  get 'fav', to: 'users#fav', as: 'fav'
  post 'pedir_plato/:id', to: 'platos#pedir_plato', as: 'pedir_plato'
  resources :restaurantes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plato
  has_many :comentario
  has_many :order
  has_one_attached :photo
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  load_and_authorize_resource
  before_action :set_restaurante, only: [:show, :aprobar_solicitud]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all

    @restaurantes.each do |restaurante|
      ratings = Comentario.where(restaurante_id: restaurante.id).pluck(:puntaje)
      if ratings.size == 0
        ratings = [0]
      end

      avg = (ratings.reduce(:+) / ratings.size.to_f).round(2)
      restaurante.update_attribute(:valoracion, avg)
    end

    # https://stackoverflow.com/questions/48219109/get-average-of-attribute-through-has-many
  end

  def aprobar_solicitud
    @restaurante = Restaurante.find(params[:id])
    @restaurante.update_attribute(:status, "aprobado")
    redirect_back fallback_location: solicitudes_path
  end

  def edit
    @restaurante = Restaurante.find(params[:id])
    # @restaurante.update_attribute(:valoracion, 3)
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
    @restaurante = Restaurante.find(params[:id])
    ratings = Comentario.where(restaurante_id: params[:id]).pluck(:puntaje)
    if ratings.size == 0
      ratings = [0]
    end

    avg = (ratings.reduce(:+) / ratings.size.to_f).round(2)
    @restaurante.update_attribute(:valoracion, avg)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurante
    ratings = Comentario.where(restaurante_id: params[:id]).pluck(:puntaje)
    if ratings.size == 0
      ratings = [0]
    end

    avg = (ratings.reduce(:+) / ratings.size.to_f).round(2)
    @restaurante.update_attribute(:valoracion, avg)
    @restaurante = Restaurante.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurante_params
    ratings = Comentario.where(restaurante_id: params[:id]).pluck(:puntaje)
    if ratings.size == 0
      ratings = [0]
    end

    avg = (ratings.reduce(:+) / ratings.size.to_f).round(2)
    @restaurante.update_attribute(:valoracion, avg)
    params.require(:restaurante).permit(:nombre, :email, :direccion, :valoracion, :photo, :imagen, :telefono)
  end
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/index.html.erb
<h1>Restaurantes</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Direccion</th>
      <th>Valoracion</th>
      <th>Imagen</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= restaurante.nombre %></td>
        <td><%= restaurante.email %></td>
        <td><%= restaurante.direccion %></td>
        <td><%= restaurante.valoracion %></td><td>
        <% if restaurante.photo.attached? %>
          <image src="<%= (url_for(restaurante.photo))%>", height="70", width="70"></image>
        <% end %>
        </td>
        <td><%= restaurante.telefono %></td>
        <td><%= link_to "<button class='btn btn-primary'>Ver</button>".html_safe, restaurante %></td>
        <td><%= link_to "<button class='btn btn-danger'>Eliminar</button>".html_safe, restaurante, method: :delete, data: { confirm: 'Estas seguro?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<button class='normalbtn'>Volver</button>".html_safe,'javascript:history.go(-1);' %>

app/views/restaurantes/mis_comentarios.html.erb
<%if current_restaurante.comentario.first %>
 <table class="table table-striped table-bordered table-condensed">
  <tr>
    <th><strong>Comentarios:</strong></th>
  </tr>

  <% current_restaurante.comentario.each do |comentario| %>
  <tr>
    <td class="td-name"><%= comentario.user.nombre+':' %></td>
    <td><%= comentario.contenido %></td>
    <td align='right'><%= comentario.fecha %></td>
    <td align='left'><%= comentario.hora %></td>
    <% if can? :edit, comentario %>
    <td align='right', width='10%'><%= link_to "<button>Editar</button>".html_safe, edit_comentario_path(comentario) %></td>
    <% end %>
  </tr>
  <% end %>
</table> 
<% else %>
<br>
  <strong>El restaurante aun no tiene comentarios</strong><br>
<br>
<br>
<% end %>

app/views/restaurantes/mis_ordenes.html.erb
<% if current_restaurante.order.first %>
<% if current_restaurante.order.first.estado != "haciendo pedido" %>

<h1>Mis ordenes</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Platos</th>
      <th>Precio</th>
      <th>Medio pago</th>
      <th>Direccion</th>
      <th>Hora entrega</th>
      <th>Estado</th>
      <th>Info</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_restaurante.order.each do |order| %>
      <tr>
        <td>

  <% cantidades = {} %>
  <% order.plato.each do |plato| %>
  <% if not plato.nombre.in? cantidades.keys %>
    <% cantidades[plato.nombre] = 1 %>
  <% else %>
    <% cantidades[plato.nombre] = cantidades[plato.nombre] + 1 %>
  <% end %>
<% end %>
  <% cantidades.keys.each do |key| %>
  <%= key + " x "%>
  <%= cantidades[key] %><br>
  <% end %>

        </td>
        <td><%= order.precio %></td>
        <td><%= order.medio_pago %></td>
        <td><%= order.direccion %></td>
        <td><%= order.hora_entrega %></td>
        <td><%= order.estado %></td>
        <td><%= order.info %></td>
        <td><%= order.user.nombre %></td>
        <% if order.estado == "pedido enviado a restaurante" %>
        <td><%= link_to "<button class='btn btn-success'>Tomar pedido</button>".html_safe, edit_order_path(order) %> </td>
        <% end %>
        <% if order.estado == "pedido tomado por restaurante" %>
        <td><%= link_to "<button class='btn btn-warning'>Marcar como pedido enviado</button>".html_safe, enviar_pedido_path(order), method: :post %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

  <% else %>
  <br>
    <strong>Aun no tienes ordenes</strong><br>
  <br>
  <br>
<% end %>
<% end %>

app/views/restaurantes/mis_platos.html.erb
<h1>Platos</h1>

<% if current_restaurante.plato.first %>
<h1>Mis Platos</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>N personas</th>
      <th>Imagen</th>
      <th>Valoracion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_restaurante.plato.each do |plato| %>
    <% if plato.id > 0 %>
      <tr>
        <td><%= plato.nombre %></td>
        <td><%= plato.precio %></td>
        <td><%= plato.descripcion %></td>
        <td><%= plato.n_personas %></td><td>
        <% if plato.photo.attached? %>
          <image src="<%= (url_for(plato.photo))%>", height="70", width="70"></image>
        <% end %>
        </td>
        <td><%= plato.valoracion %></td>
        <td><%= link_to "<button class='btn btn-primary'>Ver</button>".html_safe, plato %></td>
        <td><%= link_to "<button class='btn btn-warning'>Editar</button>".html_safe, edit_plato_path(plato) %></td>
        <td><%= link_to "<button class='btn btn-danger'>Eliminar</button>".html_safe, plato, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
  <% else %>
  <br>
    <strong>Aun no tienes platos agregados</strong><br>
  <br>
  <br>
<% end %>


<%= link_to "<button class='btn btn-success'>Crear Nuevo Plato</button>".html_safe, new_plato_path %>

app/views/restaurantes/show.html.erb
<h1 class='title'>  <strong><%= @restaurante.nombre %></strong> </h1>

<p style="text-align: center;">
<span class="glyphicon glyphicon-envelope"></span>
  <%= @restaurante.email %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<span class="glyphicon glyphicon-map-marker"></span>
  <%= @restaurante.direccion %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <strong> Valoracion:</strong>
  <%= @restaurante.valoracion %> <span class="glyphicon glyphicon-star"></span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <span class="glyphicon glyphicon-phone-alt"></span> <%= @restaurante.telefono %>
</p>

<br>


<% if can? :manage, Order and cannot? :manage, :all %>
  <% if Order.exists?(:restaurante_id => @restaurante.id, :user_id => current_user.id, :estado => "haciendo pedido") %>
    <% order = Order.find_by({:restaurante_id => @restaurante.id, :user_id => current_user.id, :estado => "haciendo pedido"}) %>
    <% if order.plato.first %>

<% order = current_user.order.find_by({:restaurante_id => @restaurante.id, :estado => "haciendo pedido"}) %>

<% cantidades = {} %>
<% precios = {} %>
<% order.plato.each do |plato| %>
  <% if not plato.nombre.in? cantidades.keys %>
    <% cantidades[plato.nombre] = 1 %>
    <% precios[plato.nombre] = plato.precio %>
  <% else %>
    <% cantidades[plato.nombre] = cantidades[plato.nombre] + 1 %>
  <% end %>
<% end %>

<% total = 0 %>
<% precios.keys.each do |plato| %>
  <% total = total + precios[plato] * cantidades[plato] %>
<% end %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Plato</th>
      <th>Precio unitario</th>
      <th>Cantidad</th>
      <th>Precio</th>
    </tr>
  </thead>

  <tbody>
    <% cantidades.each do |plato_aux| %>
      <tr>
      <% plato = Plato.find_by({:nombre => plato_aux, :restaurante_id => @restaurante.id}) %>
        <td><%= plato.nombre %></td>
        <td><%= plato.precio %></td>
        <td><%= cantidades[plato.nombre] %></td>
        <td><%= plato.precio * cantidades[plato.nombre].to_i %></td>
      </tr>
    <% end %>
    <tr><td></td><td></td><td></td><td></td></tr>
  </tbody>
  <br>
  <tfoot>
    <th> Total a pagar: </th>
    <td><span class="glyphicon glyphicon-usd"></span><%= total %></td>
    <td><%= link_to "<button class='btn btn-success'>Ir a pagar</button>".html_safe, pago_path(:restaurante_id => @restaurante.id) %></td>
    <td><%= link_to "<button class='btn btn-warning' >Cancelar pedido</button>".html_safe, order, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
  </tfoot>
</table>
      
    <% end %>
  <% else %>
    <% @order = Order.new(:user_id => current_user.id, :restaurante_id => @restaurante.id, :estado => "haciendo pedido") %>
    <% @order.save %>
    <% current_user.order.push(@order) %>
    <% @restaurante.order.push(@order) %>
    <% if Order.find_by({:restaurante_id => @restaurante.id, :user_id => current_user.id, :estado => "haciendo pedido"}).plato.first %>
      <%= link_to "<button class='normalbtn'>Finalizar pedido</button>".html_safe, pago_path(:restaurante_id => @restaurante.id) %>
    <% end %>
  <% end %>
<% end %>


<%if @restaurante.plato.first%>

<table class="table table-striped table-bordered table-condensed">

  <tbody>
      <% @restaurante.plato.each do |plato| %>
      <% if plato.id > 0 %>

      <tr>
        <td> 
        <% if plato.photo.attached? %>
        <image src="<%= (url_for(plato.photo))%>", height="200px", width="200px"></image>
        <% else %>
        <p class="glyphicon glyphicon-cutlery", style="width:200px;height:200px;"></p>
        <% end %>
        </td>

        <td>

<table class="table table-striped table-bordered table-condensed">

  <tbody>
      <tr>
        <td style="width:50%;"><h1><%= plato.nombre %></h1></td>
      </tr>
      <tr>
        <td><%= plato.descripcion %></td>
      </tr>
      <tr>
        <td><%= "Numero de personas:" %> <%= plato.n_personas %>
        <p></p>
        <span class="glyphicon glyphicon-usd"> </span> <%= plato.precio %></td>
      </tr>
      <tr>
      <td>
        <% if plato.valoracion < 0.5 %>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% elsif plato.valoracion < 1.5 %>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% elsif plato.valoracion < 2.5 %>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% elsif plato.valoracion < 3.5 %>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% elsif plato.valoracion < 4.5 %>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% else %>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <% end %>
        <%= "("+plato.valoracion.to_s+")" %>
        </td>
        
      </tr>
  </tbody>
</table>

        </td>


<td style="vertical-align: middle; text-align: center;">
<% if current_user and cannot? :manage, :all %>
<%= form_with(url: pedir_plato_path(plato), method: "post") do %>
  <%= label_tag(:pet_dog, "Cantidad") %><br>
  <%= number_field :cantidad, :cantidad %><br><br>
  <%= submit_tag "Pedir plato", class: "btn btn-danger"%><br><br>
  <% end %>
  <% end %>
<%= link_to "Ver plato", plato, class: "btn btn-warning" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

  <% else %>
  <br>
    <strong>El restaurante aun no tiene platos</strong><br>
  <br>
  <br>
<% end %>



<%if @restaurante.comentario.first %>
 <table class="table table-striped table-bordered table-condensed">
  <tr>
    <th><strong>Comentarios:</strong></th>
  </tr>

  <% @restaurante.comentario.each do |comentario| %>
  <tr>
    <td class="td-name"><%= comentario.user.nombre+':' %></td>
    <td><%= comentario.contenido %></td>
    <td align='right'><%= comentario.fecha %></td>
    <td align='left'><%= comentario.hora %></td>
    <% if can? :edit, comentario %>
    <td align='right', width='10%'><%= link_to "<button class='btn btn-primary'>Editar</button>".html_safe, edit_comentario_path(comentario) %></td>
    <% end %>
  </tr>
  <% end %>
</table> 
<% else %>
<br>
  <strong>El restaurante aun no tiene comentarios</strong><br>

<% end %>


<% if current_user %>
<% if can? :create, Comentario and cannot? :manage, :all %>
<% @comentario = Comentario.new %>
<%= render 'comentarios/form', comentario: @comentario %>
<% end %>

<br>
<% if current_user.admin == false %>
<% if @restaurante.nombre.in? current_user.rest_fav %>
<%= link_to "<button class='btn btn-primary'>Eliminar de favoritos</button>".html_safe, delete_fav_path(:id => current_user.id, :nombre => @restaurante.nombre), method: :post %>
<% else %>
<%= link_to "<button class='btn btn-primary'>Agregar restaurantes a favoritos</button>".html_safe, add_fav_path(:id => current_user.id, :nombre => @restaurante.nombre), method: :post %>
<% end %>
<% end %>
<% end %>

<%= link_to "<button class='btn btn-primary'>Volver</button>".html_safe, 'javascript:history.go(-1);' %>

app/views/restaurantes/solicitudes.html.erb
<h1>Solicutudes Restaurantes</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Direccion</th>
      <th>Valoracion</th>
      <th>Imagen</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
    <% if restaurante.status == "pendiente" %>
      <tr>
        <td><%= restaurante.nombre %></td>
        <td><%= restaurante.email %></td>
        <td><%= restaurante.direccion %></td>
        <td><%= restaurante.valoracion %></td>
        <td><%= restaurante.imagen %></td>
        <td><%= restaurante.telefono %></td>
        <td><%= link_to "<button class='btn btn-success'>Aprobar</button>".html_safe, aprobar_path(restaurante), method: :post %></td>
        <td><%= link_to "<button class='btn btn-danger'>Eliminar</button>".html_safe, restaurante, method: :delete, data: { confirm: 'Estas seguro?' }  %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<button class='btn btn-primary'>Volver</button>".html_safe,'javascript:history.go(-1);' %>