config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :comentarios
  resources :platos
  devise_for :users
  devise_for :restaurantes
  get 'home/index'
  get 'solicitudes', to: 'restaurantes#solicitudes'
  post 'aprobar/:id', to: 'restaurantes#aprobar_solicitud', as: 'aprobar'
  post 'enviar_pedido/:id', to: 'orders#enviar_pedido', as: 'enviar_pedido'
  post 'finalizar_pedido/:id', to: 'orders#finalizar_pedido', as: 'finalizar_pedido'
  get 'pago/:restaurante_id', to: 'orders#pago', as: 'pago'
  get 'mis_platos', to: 'restaurantes#mis_platos', as: 'mis_platos'
  get 'mis_comentarios', to: 'restaurantes#mis_comentarios', as: 'mis_comentarios'
  get 'mis_ordenes', to: 'restaurantes#mis_ordenes', as: 'mis_ordenes'
  post 'add_fav/:id/:nombre', to: 'users#add_fav', as: 'add_fav'
  post 'delete_fav/:nombre', to: 'users#delete_fav', as: 'delete_fav'
  get 'pedidos_usuario', to: 'users#pedidos_usuario', as: 'pedidos_usuario'
  get 'fav', to: 'users#fav', as: 'fav'
  post 'pedir_plato/:id', to: 'platos#pedir_plato', as: 'pedir_plato'
  resources :restaurantes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comentario
  has_many :order
  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :add_fav, :delete_fav]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def add_fav
    restaurante = params[:nombre]
    current_user.rest_fav.push(restaurante)
    current_user.save
    redirect_back(fallback_location: root_path)
  end

  def delete_fav
    restaurante = params[:nombre]
    current_user.rest_fav.delete(restaurante)
    current_user.save
    redirect_back(fallback_location: root_path)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:nombre, :correo, :direccion, :imagen)
  end
end

app/views/users/fav.html.erb
<h1>Restaurantes Favoritos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Direccion</th>
      <th>Valoracion</th>
      <th>Imagen</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.rest_fav.each do |restaurante_nombre| %>
      <tr>
      <% restaurante = Restaurante.find_by({:nombre => restaurante_nombre}) %>
        <td><%= restaurante.nombre %></td>
        <td><%= restaurante.email %></td>
        <td><%= restaurante.direccion %></td>
        <td><%= restaurante.valoracion %></td>
        <td><%= restaurante.imagen %></td>
        <td><%= restaurante.telefono %></td>
        <td><%= link_to "<button class='btn btn-warning'>Ver</button>".html_safe, restaurante %></td>
        <td><%= link_to "<button class='btn btn-danger'>Eliminar de favoritos</button>".html_safe, delete_fav_path(:id => current_user.id, :nombre => restaurante.nombre), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<button class='btn btn-primary'>Volver</button>".html_safe,'javascript:history.go(-1);' %>

app/views/users/index.html.erb
<h1>Usuarios</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Direccion</th>
      <th>Imagen</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.email %></td>
        <td><%= user.direccion %></td>
        <td>
        <% if user.photo.attached? %>
          <image src="<%= (url_for(user.photo))%>", height="70", width="70"></image>
        <% end %>
        </td>
        <td><%= link_to "<button class='btn btn-primary'>Ver</button>".html_safe, user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<button class='btn btn-primary'>Volver</button>".html_safe, 'javascript:history.go(-1);' %>

app/views/users/pedidos_usuario.html.erb
<% orders = Order.all %>
<% orders.each do |order| %>
  <% if order.estado == "haciendo pedido" and not order.plato.first %>
  <% order.destroy %>
  <% end %>
<% end %>


<h1>Mis pedidos</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Platos</th>
      <th>Precio</th>
      <th>Medio pago</th>
      <th>Direccion</th>
      <th>Hora entrega</th>
      <th>Estado</th>
      <th>Info</th>
      <th>Restaurante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.order.each do |order| %>
      <tr>
        <td>

  <% cantidades = {} %>
  <% order.plato.each do |plato| %>
  <% if not plato.nombre.in? cantidades.keys %>
    <% cantidades[plato.nombre] = 1 %>
  <% else %>
    <% cantidades[plato.nombre] = cantidades[plato.nombre] + 1 %>
  <% end %>
<% end %>
  <% cantidades.keys.each do |key| %>
  <%= key + " x "%>
  <%= cantidades[key] %><br>
  <% end %>

        </td>
        <td><%= order.precio %></td>
        <td><%= order.medio_pago %></td>
        <td><%= order.direccion %></td>
        <td><%= order.hora_entrega %></td>
        <td><%= order.estado %></td>
        <td><%= order.info %></td>
        <td><%= order.restaurante.nombre %></td>
        <% if order.estado == "pedido enviado a restaurante" %>
        <td><%= link_to "<button class='btn btn-danger'>Cancelar pedido</button>".html_safe, order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if order.estado == "pedido enviado" %>
        <td><%= link_to "<button class='btn btn-warning'>Marcar como recibido</button>".html_safe, finalizar_pedido_path(order), method: :post %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<button class='btn btn-primary'>Volver</button>".html_safe, 'javascript:history.go(-1);' %>

app/views/users/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @user.direccion %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @user.imagen %>
</p>

<%= link_to "<button class='normalbtn'>Volver</button>".html_safe, 'javascript:history.go(-1);' %>