config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :comentarios
  resources :platos
  devise_for :users
  devise_for :restaurantes
  get 'home/index'
  get 'solicitudes', to: 'restaurantes#solicitudes'
  post 'aprobar/:id', to: 'restaurantes#aprobar_solicitud', as: 'aprobar'
  post 'enviar_pedido/:id', to: 'orders#enviar_pedido', as: 'enviar_pedido'
  post 'finalizar_pedido/:id', to: 'orders#finalizar_pedido', as: 'finalizar_pedido'
  get 'pago/:restaurante_id', to: 'orders#pago', as: 'pago'
  get 'mis_platos', to: 'restaurantes#mis_platos', as: 'mis_platos'
  get 'mis_comentarios', to: 'restaurantes#mis_comentarios', as: 'mis_comentarios'
  get 'mis_ordenes', to: 'restaurantes#mis_ordenes', as: 'mis_ordenes'
  post 'add_fav/:id/:nombre', to: 'users#add_fav', as: 'add_fav'
  post 'delete_fav/:nombre', to: 'users#delete_fav', as: 'delete_fav'
  get 'pedidos_usuario', to: 'users#pedidos_usuario', as: 'pedidos_usuario'
  get 'fav', to: 'users#fav', as: 'fav'
  post 'pedir_plato/:id', to: 'platos#pedir_plato', as: 'pedir_plato'
  resources :restaurantes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Proyecto</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div class="sidebar">
    
  <%= link_to "Inicio", home_index_path, class: "btn btn-link" %>

<% if can? :manage, :all %>
<%= link_to "Usuarios", users_path, class: "btn btn-link" %>
<%= link_to "Restaurantes", restaurantes_path, class: "btn btn-link" %>
<%= link_to "Platos", platos_path, class: "btn btn-link" %>
<%= link_to "Ordenes", orders_path, class: "btn btn-link" %>
<%= link_to "Comentarios", comentarios_path, class: "btn btn-link" %>
<%= link_to "Solicitudes Restaurantes", solicitudes_path, class: "btn btn-link" %>
<% end %>

<% if can? :update, current_user and cannot? :manage, :all%>
<%= link_to "Mis pedidos", pedidos_usuario_path, class: "btn btn-link" %>
<%= link_to "Mis restaurantes favoritos", fav_path, class: "btn btn-link" %>
<% end %>

<% if current_restaurante %>
<%= link_to "Mis platos", mis_platos_path, class: "btn btn-link" %>
<%= link_to "Mis comentarios", mis_comentarios_path, class: "btn btn-link" %>
<%= link_to "Mis ordenes", mis_ordenes_path, class: "btn btn-link" %>
<% end %>
  </div>

  <div class="content">

  <!-- creamos una barra de botones -->
  <ul class="tab">
  
    <% if user_signed_in? %>
    <!-- creamos boton salir (log out) -->
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Cerrar Sesion</button>".html_safe, destroy_user_session_path, method: :delete %>
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Editar cuenta/Borrar cuenta</button>".html_safe, edit_user_registration_path %>
    <% elsif restaurante_signed_in? %>
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Cerrar Sesion</button>".html_safe, destroy_restaurante_session_path, method: :delete %>
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Editar Restaurant/Borrar Restaurant</button>".html_safe, edit_restaurante_registration_path %>
    <% else %>
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Solicitar Creacion Restaurante</button>".html_safe, new_restaurante_registration_path %>
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Iniciar Sesion Restaurante</button>".html_safe, new_restaurante_session_path %>
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Registrarse</button>".html_safe, new_user_registration_path %>
      <%= link_to "<button class='btn btn-primary', style='float: right;'>Iniciar Sesion</button>".html_safe, new_user_session_path %>
    <% end %>
  </ul>
  <br>

  <%= yield %>
</body>

</html>